var mergefields =
[ //############################################################################
  {'label':'header',        'value':'Buyer'},
  //############################################################################

    {'label':'subheader',                         'value':'Agency Representation'},
      {'label':'Agreement Commencement Date',     'value':'Deal: Listing Agreement Commencement Date|date_format:"F j, Y"'},
      {'label':'Agreement Expiration Date',       'value':'Deal: Listing Agreement Expiration Date|date_format:"F j, Y"'},
      {'label':'Gross Listing Commission $',      'value':'Deal: Gross Listing Commission Dollars|number_format:2'},
      {'label':'Gross Listing Commission %',      'value':'Deal: Gross Listing Commission Percent|number_format:2'},
      {'label':'Representation Term (months)',    'value':'Deal: Listing Agreement Term Months'},
      {'label':'Cap Rate(%)',    'value':'Deal: Cap Rate Percent'},
	  
	 {'label':'subheader',                       'value':'Sale Details'},
		{'label':'Total Sales Price',   'value':'Total Sales Price'},
		{'label':'Per Square Foot Cost',   'value':'Per Square Foot Cost'},
		{'label':'Cap Rate Percent',   'value':'Cap Rate Percent|number_format:2'},
		{'label':'Close Date',   'value':'Close Date||date_format:"F j, Y"'},
	
	{'label':'subheader',                       'value':'Due Deligence Peroid'},
		{'label':'Due Diligence Period Expiration Date',   'value':'Due Diligence Period Expiration Date|date_format:"F j, Y"'},
		{'label':'Earnest Money Amount',   'value':'Earnest Money Amount|number_format:2'},
		{'label':'Earnest Money Held By',   'value':'Earnest Money Held By'},
		{'label':'Earnest Money Hard 1',   'value':'Earnest Money Hard 1|number_format|2'},
		{'label':'Due Diligence Period 1 Status',   'value':'Due Diligence Period 1 Status'},
		
	{'label':'subheader',                       'value':'Additional Due Deligence Peroid'},
		{'label':'Due Diligence Period 2 Expiration Date',   'value':'Due Diligence Period 2 Expiration Date|date_format:"F j, Y"'},
		{'label':'Earnest Money Amount 2',   'value':'Earnest Money Amount 2|number_format:2'},
		{'label':'Earnest Money Held By 2',   'value':'Earnest Money Held By 2'},
		{'label':'Earnest Money Hard 2',   'value':'Earnest Money Hard 2|number_format|2'},
		{'label':'Due Diligence Period 2 Status',   'value':'Due Diligence Period 2 Status'},
		
	
	{'label':'subheader',                       'value':'Commission'},
		{'label':'Transaction Amount',   'value':'Transaction Amount'},
		{'label':'Square Footage',   'value':'Square Footage|number_format:2'},
		{'label':'Rate Type',   'value':'Rate Type'},
		{'label':'Total Rate Dollar',   'value':'Total Rate Dollar|number_format:2'},
		{'label':'Total Gross Value',   'value':'Total Gross Value'},
		{'label':'In House Commission Percent',   'value':'In House Commission Percent|number_format:2'},
		{'label':'In House Commission Amount',   'value':'In House Commission Amount'},
		{'label':'External Commission Percent',   'value':'External Commission Percent|number_format:2'},
		{'label':'External Commission Amount',   'value':'External Commission Amount|number_format:2'},
		{'label':'External Company',   'value':'External Company'},
		{'label':'Commission Notes',   'value':'Commission Notes'},
		

    {'label':'subheader',         'value':'Search Requirements'},
      {'label':'Square Footage',  'value':'Search Square Footage'},
      {'label':'Property Type',   'value':'Search Property Type'},
      {'label':'Market/Subtype',  'value':'Search Market/Submarket'},
      {'label':'Parking Spaces',  'value':'Search Parking Spaces'},
      {'label':'Price',           'value':'Search Price|number_format:2'},

    {'label':'subheader',       'value':'Buyer (Primary Contact)'},
      {'label':'Full Name',     'value':'Primary Buyer Contact: Full Name'},
      {'label':'First Name',    'value':'Primary Buyer Contact: First Name'},
      {'label':'Last Name',     'value':'Primary Buyer Contact: Last Name'},
      {'label':'Title',         'value':'Primary Buyer Contact: Title'},
      {'label':'Department',    'value':'Primary Buyer Contact: Department'},
      {'label':'Email',         'value':'Primary Buyer Contact: Email'},
      {'label':'Fax',           'value':'Primary Buyer Contact: Business Fax'},
      {'label':'Phone',         'value':'Primary Buyer Contact: Business Phone'},
      {'label':'Mobile Phone',  'value':'Primary Buyer Contact: Mobile Phone'},

  //############################################################################
  {'label':'header',                            'value':'Seller'},
  //############################################################################

    {'label':'subheader',                       'value':'Agreement Details'},
      {'label':'Agreement Commencement Date',     'value':'Deal: Listing Agreement Commencement Date|date_format:"F j, Y"'},
      {'label':'Agreement Expiration Date',       'value':'Deal: Listing Agreement Expiration Date|date_format:"F j, Y"'},
      {'label':'Gross Listing Commission $',      'value':'Deal: Gross Listing Commission Dollars|number_format:2'},
      {'label':'Gross Listing Commission %',      'value':'Deal: Gross Listing Commission Percent|number_format:2'},
      {'label':'Representation Term (months)',    'value':'Deal: Listing Agreement Term Months'},
      {'label':'Cap Rate(%)',    'value':'Deal: Cap Rate Percent'},
     {'label':'Asking Price',    'value':'Deal: Asking Price'},
	  
	{'label':'subheader',                       'value':'Sale Details'},
		{'label':'Total Sales Price',   'value':'Total Sales Price'},
		{'label':'Per Square Foot Cost',   'value':'Per Square Foot Cost'},
		{'label':'Cap Rate Percent',   'value':'Cap Rate Percent|number_format:2'},
		{'label':'Close Date',   'value':'Close Date||date_format:"F j, Y"'},
	
	{'label':'subheader',                       'value':'Due Deligence Peroid'},
		{'label':'Due Diligence Period Expiration Date',   'value':'Due Diligence Period Expiration Date|date_format:"F j, Y"'},
		{'label':'Earnest Money Amount',   'value':'Earnest Money Amount|number_format:2'},
		{'label':'Earnest Money Held By',   'value':'Earnest Money Held By'},
		{'label':'Earnest Money Hard 1',   'value':'Earnest Money Hard 1|number_format|2'},
		{'label':'Due Diligence Period 1 Status',   'value':'Due Diligence Period 1 Status'},
		
	{'label':'subheader',                       'value':'Additional Due Deligence Peroid'},
		{'label':'Due Diligence Period 2 Expiration Date',   'value':'Due Diligence Period 2 Expiration Date|date_format:"F j, Y"'},
		{'label':'Earnest Money Amount 2',   'value':'Earnest Money Amount 2|number_format:2'},
		{'label':'Earnest Money Held By 2',   'value':'Earnest Money Held By 2'},
		{'label':'Earnest Money Hard 2',   'value':'Earnest Money Hard 2|number_format|2'},
		{'label':'Due Diligence Period 2 Status',   'value':'Due Diligence Period 2 Status'},
		
	
	{'label':'subheader',                       'value':'Commission'},
		{'label':'Transaction Amount',   'value':'Transaction Amount'},
		{'label':'Square Footage',   'value':'Square Footage|number_format:2'},
		{'label':'Rate Type',   'value':'Rate Type'},
		{'label':'Total Rate Dollar',   'value':'Total Rate Dollar|number_format:2'},
		{'label':'Total Gross Value',   'value':'Total Gross Value'},
		{'label':'In House Commission Percent',   'value':'In House Commission Percent|number_format:2'},
		{'label':'In House Commission Amount',   'value':'In House Commission Amount'},
		{'label':'External Commission Percent',   'value':'External Commission Percent|number_format:2'},
		{'label':'External Commission Amount',   'value':'External Commission Amount|number_format:2'},
		{'label':'External Company',   'value':'External Company'},
		{'label':'Commission Notes',   'value':'Commission Notes'},
		

    

  //############################################################################
  {'label':'header',                            'value':'Landlord'},
  //############################################################################

    {'label':'subheader',                       'value':'Agreement Details'},
      {'label':'Agreement Commencement Date',   'value':'Listing Agreement Commencement Date|date_format:"F j, Y"'},
      {'label':'Agreement Expiration Date',     'value':'Listing Agreement Expiration Date|date_format:"F j, Y"'},
      {'label':'Listing Term',                  'value':'Listing Agreement Term Months'},
      {'label':'Gross Listing Commission %',    'value':'Gross Commission Percentage|number_format:2'},
      {'label':'Listing Rental Rate $',         'value':'Search Yearly Square Foot Rate|number_format:2'},
      {'label':'Projected Rental Increase',     'value':'Search Yearly Square Foot Rate Increase|number_format:2'},
      {'label':'Projected Term (Years)',        'value':'Term Years'},
	  
	  {'label':'subheader',                               'value':'Lease Details'},
      {'label':'Lease Commencement Date',                 'value':'Lease Commencement Date|date_format:"F j, Y"'},
      {'label':'Lease Expiration Date',                   'value':'Lease Expiration Date|date_format:"F j, Y"'},
      {'label':'Lease Term (Months)',         			  'value':'Lease Term Months'},
      {'label':'Lease Execution Date',    				  'value':'Lease Execution Date|date_format:"F j, Y"'},
      {'label':'Lease Possession Date',            		  'value':'Lease Possession Date|date_format:"F j, Y"'},
      {'label':'Lease Type',                   			  'value':'Lease Type'},
	  {'label':'Base Rate',                   			  'value':'Base Rate|number_format:2'},
	  {'label':'Annual Rate Increase',                    'value':'Annual Rate Increase'},
	  {'label':'Annual Rate Increase(%)',                 'value':'Annual Rate Increase(%)'},
	  {'label':'Annual Rate Increase Type',               'value':'Annual Rate Increase Type'},
	  {'label':'Base Year',                    			  'value':'Base Year'},
	  {'label':'Security Deposit',                    	  'value':'Security Deposit'},
	  {'label':'Security Deposit Amount',                 'value':'Security Deposit Amount|number_format:2'},
	  {'label':'Security Deposit Held By',                 'value':'Security Deposit Held By'},
	  {'label':'Improvement Allowance',                 'value':'Improvement Allowance|number_format:2'},
	  {'label':'Average Rent',                 			'value':'Average Rent|number_format:2'},
	  {'label':'Free Rent',                 			'value':'Free Rent|number_format:2'},
	  
	  
	  
	   {'label':'subheader',                               'value':'Tenant Options'},
      {'label':'Option to Renew Expiration Date',                    'value':'Option to Renew Expiration Date|date_format:"F j, Y"'},
      {'label':'Option to Terminate Expiration Date',                   'value':'Option to Terminate Expiration Date|date_format:"F j, Y"'},
      {'label':'Option to Purchase Expiration Date',         			  'value':'Option to Purchase Expiration Datedate_format:"F j, Y"'},
	  {'label':'Additional Concessions',         			  'value':'Additional Concessions'},
	  
	  
	 {'label':'subheader',                               'value':'Commission Cashout '},
      {'label':'Cashout Commission Checkbox',      		  'value':'Cashout Commission Checkbox'},
	  {'label':'Transaction Amount',                      'value':'Transaction Amount|number_format:2'},
	  {'label':'Square Footage',                      'value':'Square Footage|number_format:2'},
	  {'label':'Rate Type',                      'value':'Rate Type|number_format:2'},
	  {'label':'Total Rate Dollar',                      'value':'Total Rate Dollar|number_format:2'},
	  {'label':'Total Rate Dollar Per SF',                      'value':'Total Rate Dollar Per SF|number_format:2'},
	  {'label':'Total Rate Percent',                      'value':'Total Rate Percent'},
	  {'label':'Total Gross Value',                      'value':'Total Gross Value'},
	  {'label':'In House Commission Percent',                      'value':'In House Commission Percent|number_format:2'},
	  {'label':'In House Commission Amount',                      'value':'In House Commission Amount'},
	  {'label':'External Commission Percent',                      'value':'External Commission Percent|number_format:2'},
	  {'label':'External Commission Amount',                      'value':'External Commission Amount'},
	  {'label':'External Company',                      'value':'External Company'},
	  {'label':'Commission Notes',                      'value':'Commission Notes'},
	  {'label':'Transaction Amount',                      'value':'Transaction Amount|number_format:2'},
	  
	  
	  {'label':'subheader',                               'value':'Commission Residual'},
	  {'label':'Residual Commission Months',                      'value':'Residual Commission Months'},
	  {'label':'Residual Commission First Mo Dollars',                      'value':'Residual Commission First Mo Dollars|number_format:2'},
	  {'label':'Residual Commission Remaining Mo Percent',                      'value':'Residual Commission Remaining Mo Percent|number_format:2'},
	  {'label':'Residual Total Rate Percent',                      'value':'Residual Total Rate Percent'},
	  {'label':'Residual Total Gross Value',                      'value':'Residual Total Gross Value'},
	  {'label':'Residual In House Commission Percent',                      'value':'Residual In House Commission Percent|number_format:2'},
	  {'label':'Residual In House Commission Amount',                      'value':'Residual In House Commission Amount'},
	  {'label':'Residual External Commission Percent',                      'value':'Residual External Commission Percent|number_format:2'},
	  {'label':'Residual External Commission Amount',                      'value':'Residual External Commission Amount'},
	  
	  
  //############################################################################
  {'label':'header',                                      'value':'Tenant'},
  //############################################################################

    {'label':'subheader',                                 'value':'Agency Representation'},
      {'label':'Agreement Commencement Date',     'value':'Deal: Listing Agreement Commencement Date|date_format:"F j, Y"'},
      {'label':'Agreement Expiration Date',       'value':'Deal: Listing Agreement Expiration Date|date_format:"F j, Y"'},
      {'label':'Gross Listing Commission $',      'value':'Deal: Gross Listing Commission Dollars|number_format:2'},
      {'label':'Gross Listing Commission %',      'value':'Deal: Gross Listing Commission Percent|number_format:2'},
      {'label':'Representation Term (months)',    'value':'Deal: Listing Agreement Term Months'},
      {'label':'Type',    'value':'Deal: Type'},
	  
	  {'label':'subheader',                               'value':'Lease Details'},
      {'label':'Lease Commencement Date',                 'value':'Lease Commencement Date|date_format:"F j, Y"'},
      {'label':'Lease Expiration Date',                   'value':'Lease Expiration Date|date_format:"F j, Y"'},
      {'label':'Lease Term (Months)',         			  'value':'Lease Term Months'},
      {'label':'Lease Execution Date',    				  'value':'Lease Execution Date|date_format:"F j, Y"'},
      {'label':'Lease Possession Date',            		  'value':'Lease Possession Date|date_format:"F j, Y"'},
      {'label':'Lease Type',                   			  'value':'Lease Type'},
	  {'label':'Base Rate',                   			  'value':'Base Rate|number_format:2'},
	  {'label':'Annual Rate Increase',                    'value':'Annual Rate Increase'},
	  {'label':'Annual Rate Increase(%)',                 'value':'Annual Rate Increase(%)'},
	  {'label':'Annual Rate Increase Type',               'value':'Annual Rate Increase Type'},
	  {'label':'Base Year',                    			  'value':'Base Year'},
	  {'label':'Security Deposit',                    	  'value':'Security Deposit'},
	  {'label':'Security Deposit Amount',                 'value':'Security Deposit Amount|number_format:2'},
	  {'label':'Security Deposit Held By',                 'value':'Security Deposit Held By'},
	  {'label':'Improvement Allowance',                 'value':'Improvement Allowance|number_format:2'},
	  {'label':'Average Rent',                 			'value':'Average Rent|number_format:2'},
	  {'label':'Free Rent',                 			'value':'Free Rent|number_format:2'},
	  
	  
	  {'label':'subheader',                               'value':'Tenant Options'},
      {'label':'Option to Renew Expiration Date',                    'value':'Option to Renew Expiration Date|date_format:"F j, Y"'},
      {'label':'Option to Terminate Expiration Date',                   'value':'Option to Terminate Expiration Date|date_format:"F j, Y"'},
      {'label':'Option to Purchase Expiration Date',         			  'value':'Option to Purchase Expiration Datedate_format:"F j, Y"'},
	  {'label':'Additional Concessions',         			  'value':'Additional Concessions'},
	  
	  
	  
	  {'label':'subheader',                               'value':'Commission Cashout '},
      {'label':'Cashout Commission Checkbox',      		  'value':'Cashout Commission Checkbox'},
	  {'label':'Transaction Amount',                      'value':'Transaction Amount|number_format:2'},
	  {'label':'Square Footage',                      'value':'Square Footage|number_format:2'},
	  {'label':'Rate Type',                      'value':'Rate Type|number_format:2'},
	  {'label':'Total Rate Dollar',                      'value':'Total Rate Dollar|number_format:2'},
	  {'label':'Total Rate Dollar Per SF',                      'value':'Total Rate Dollar Per SF|number_format:2'},
	  {'label':'Total Rate Percent',                      'value':'Total Rate Percent'},
	  {'label':'Total Gross Value',                      'value':'Total Gross Value'},
	  {'label':'In House Commission Percent',                      'value':'In House Commission Percent|number_format:2'},
	  {'label':'In House Commission Amount',                      'value':'In House Commission Amount'},
	  {'label':'External Commission Percent',                      'value':'External Commission Percent|number_format:2'},
	  {'label':'External Commission Amount',                      'value':'External Commission Amount'},
	  {'label':'External Company',                      'value':'External Company'},
	  {'label':'Commission Notes',                      'value':'Commission Notes'},
	  {'label':'Transaction Amount',                      'value':'Transaction Amount|number_format:2'},
	  
	  
	  {'label':'subheader',                               'value':'Commission Residual'},
	  {'label':'Residual Commission Months',                      'value':'Residual Commission Months'},
	  {'label':'Residual Commission First Mo Dollars',                      'value':'Residual Commission First Mo Dollars|number_format:2'},
	  {'label':'Residual Commission Remaining Mo Percent',                      'value':'Residual Commission Remaining Mo Percent|number_format:2'},
	  {'label':'Residual Total Rate Percent',                      'value':'Residual Total Rate Percent'},
	  {'label':'Residual Total Gross Value',                      'value':'Residual Total Gross Value'},
	  {'label':'Residual In House Commission Percent',                      'value':'Residual In House Commission Percent|number_format:2'},
	  {'label':'Residual In House Commission Amount',                      'value':'Residual In House Commission Amount'},
	  {'label':'Residual External Commission Percent',                      'value':'Residual External Commission Percent|number_format:2'},
	  {'label':'Residual External Commission Amount',                      'value':'Residual External Commission Amount'},
		
	  

  //############################################################################
  {'label':'header',                        'value':'Property'},
  //############################################################################

    {'label':'subheader',                   'value':'Property Information'},
      {'label':'Property Type',             'value':'Search Property Type'},
{'label':'Property Name',             'value':'Property: Property Name'},
{'label': 'Acreage','value': 'Property: Acreage|number_format:2'},
{'label': 'Additional Features 1','value': 'Property: Additional Features 1'},
{'label': 'Additional Features 2','value': 'Property: Additional Features 2'},
{'label': 'Additional Listing Details','value': 'Property: Additional Listing Details'},
{'label': 'Additional Property Details','value': 'Property: Additional Property Details'},
{'label': 'Additional Strip','value': 'Property: Additional Strip'},
{'label': 'Address','value': 'Property: Address'},
{'label': 'Anchor Tenant','value': 'Property: Anchor Tenant'},
{'label': 'Available RSF','value': 'Property: Available RSF'},
{'label': 'Avg Daily Rate','value': 'Property: Avg Daily Rate'},
{'label': 'Cal Base Rate','value': 'Property: Cal Base Rate|number_format:2'},
{'label': 'Cap Rate 1 Dollars','value': 'Property: Cap Rate 1 Dollars|number_format:2'},
{'label': 'Cap Rate 1 Percent','value': 'Property: Cap Rate 1 Percent|number_format:3'},
{'label': 'Cap Rate 2 Dollars','value': 'Property: Cap Rate 2 Dollars|number_format:2'},
{'label': 'Cap Rate 2 Percent','value': 'Property: Cap Rate 2 Percent|number_format:3'},
{'label': 'Cap Rate 3 Dollars','value': 'Property: Cap Rate 3 Dollars|number_format:2'},
{'label': 'Cap Rate 3 Percent','value': 'Property: Cap Rate 3 Percent|number_format:3'},
{'label': 'Ceiling Height','value': 'Property: Ceiling Height'},
{'label': 'City','value': 'Property: City'},
{'label': 'Common Area Factor','value': 'Property: Common Area Factor'},
{'label': 'Construction Date','value': 'Property: Construction Datedate_format:"F j, Y"'},
{'label': 'Contiguous SF','value': 'Property: Contiguous SF'},
{'label': 'Country','value': 'Property: Country'},
{'label': 'County','value': 'Property: County'},
{'label': 'Curb Cuts','value': 'Property: Curb Cuts'},
{'label': 'Daily Car Count','value': 'Property: Daily Car Count'},
{'label': 'Description','value': 'Property: Description'},
{'label': 'Divisible Min SF','value': 'Property: Divisible Min SF'},
{'label': 'Dock Height Doors','value': 'Property: Dock Height Doors'},
{'label': 'Elevators','value': 'Property: Elevators'},
{'label': 'Environmental','value': 'Property: Environmental'},
{'label': 'Floors','value': 'Property: Floors'},
{'label': 'Grade Level Doors','value': 'Property: Grade Level Doors'},
{'label': 'Image Primary 720x480','value': 'Property: Image Primary 720x480'},
{'label': 'Image Primary','value': 'Property: Image Primary'},
{'label': 'Image Secondary 720x480','value': 'Property: Image Secondary 720x480'},
{'label': 'Image Secondary','value': 'Property: Image Secondary'},
{'label': 'Image Tertiary 720x480','value': 'Property: Image Tertiary 720x480'},
{'label': 'Image Tertiary','value': 'Property: Image Tertiary'},
{'label': 'Leased RSF','value': 'Property: Leased RSF'},
{'label': 'Listing Agreement Commencement Date','value': 'Property: Listing Agreement Commencement Date|date_format:"F j, Y"'},
{'label': 'Listing Agreement Expiration Date','value': 'Property: Listing Agreement Expiration Date|date_format:"F j, Y"'},
{'label': 'Major Intersection','value': 'Property: Major Intersection'},
{'label': 'Major Thoroughfare','value': 'Property: Major Thoroughfare'},
{'label': 'Market','value': 'Property: Market'},
{'label': 'Name Strip 1','value': 'Property: Name Strip 1'},
{'label': 'Name Strip 2','value': 'Property: Name Strip 2'},
{'label': 'Natural Gas','value': 'Property: Natural Gas'},
{'label': 'Net Operating Income','value': 'Property: Net Operating Income|number_format:2'},
{'label': 'Number Of Signs','value': 'Property: Number Of Signs'},
{'label': 'Number Of Units','value': 'Property: Number Of Units'},
{'label': 'Office Space','value': 'Property: Office Space'},
{'label': 'Operating Expense Insurance Yr','value': 'Property: Operating Expense Insurance Yr|number_format:2'},
{'label': 'Operating Expense Insurance','value': 'Property: Operating Expense Insurance|number_format:2'},
{'label': 'Operating Expense Janitorial Yr','value': 'Property: Operating Expense Janitorial Yr|number_format:2'},
{'label': 'Operating Expense Janitorial','value': 'Property: Operating Expense Janitorial|number_format:2'},
{'label': 'Operating Expense Other Yr','value': 'Property: Operating Expense Other Yr|number_format:2'},
{'label': 'Operating Expense Other','value': 'Property: Operating Expense Other|number_format:2'},
{'label': 'Operating Expense Taxes Yr','value': 'Property: Operating Expense Taxes Yr|number_format:2'},
{'label': 'Operating Expense Taxes','value': 'Property: Operating Expense Taxes|number_format:2'},
{'label': 'Operating Expense Total Yr','value': 'Property: Operating Expense Total Yr|number_format:2'},
{'label': 'Operating Expense Total','value': 'Property: Operating Expense Total|number_format:2'},
{'label': 'Operating Expense Utilities Yr','value': 'Property: Operating Expense Utilities Yr|number_format:2'},
{'label': 'Operating Expense Utilities','value': 'Property: Operating Expense Utilities|number_format:2'},
{'label': 'Other Doors','value': 'Property: Other Doors'},
{'label': 'Ownership Name Legal Entity','value': 'Property: Ownership Name Legal Entity'},
{'label': 'Parking Available','value': 'Property: Parking Available'},
{'label': 'Parking Ratio','value': 'Property: Parking Ratio'},
{'label': 'Plate SF','value': 'Property: Plate SF'},
{'label': 'Postal Code','value': 'Property: PostalCode'},
{'label': 'Power','value': 'Property: Power'},
{'label': 'Property Additional Features','value': 'Property: Property Additional Features'},
{'label': 'Property Class','value': 'Property: Property Class'},
{'label': 'Property Comments','value': 'Property: Property Comments'},
{'label': 'Property Stake','value': 'Property: Property Stake'},
{'label': 'Property Valuation','value': 'Property: Property Valuation'},
{'label': 'Rail','value': 'Property: Rail'},
{'label': 'Rennovation Date','value': 'Property: Rennovation Date|date_format:"F j, Y"'},
{'label': 'RevPAR','value': 'Property: RevPAR'},
{'label': 'Sewer','value': 'Property: Sewer'},
{'label': 'Sign Information','value': 'Property: Sign Information'},
{'label': 'Sign Placement','value': 'Property: Sign Placement'},
{'label': 'Sign Request History','value': 'Property: Sign Request History'},
{'label': 'Sign Request Recipient','value': 'Property: Sign Request Recipient'},
{'label': 'Sign Single Double','value': 'Property: Sign Single Double'},
{'label': 'Sign Type','value': 'Property: Sign Type'},
{'label': 'Sprinklers','value': 'Property: Sprinklers'},
{'label': 'Stake GPS','value': 'Property: Stake GPS'},
{'label': 'Standing Construction','value': 'Property: Standing Construction'},
{'label': 'State','value': 'Property: State'},
{'label': 'Sub Market','value': 'Property: Sub Market'},
{'label': 'Sub Type','value': 'Property: Sub Type'},
{'label': 'Sublease','value': 'Property: Sublease'},
{'label': 'Suite','value': 'Property: Suite'},
{'label': 'Tax ID Number','value': 'Property: Tax ID Number'},
{'label': 'Tenant Type','value': 'Property: Tenant Type'},
{'label': 'Total Building Size','value': 'Property: Total Building Size'},
{'label': 'Type','value': 'Property: Type'},
{'label': 'Vacant','value': 'Property: Vacant'},
{'label': 'Washer/Dryer','value': 'Property: Washer Dryer'},
{'label': 'Water','value': 'Property: Water'},
{'label': 'Yard','value': 'Property: Yard'},
{'label': 'Year Built','value': 'Property: Year Built'},
{'label': 'Year rennovated','value': 'Property: Year rennovated'},
{'label': 'Yearly Rent','value': 'Property: Yearly Rent|number_format:2'},
{'label': 'Zoning','value': 'Property: Zoning'},
	  
	  
    {'label':'subheader',         'value':'Images'},
      {'label':'Primary Image',   'value':'Property: Image Primary Public'},
      {'label':'Secondary Image', 'value':'Property: Image Secondary Public'},
      {'label':'Tertiary Image',  'value':'Property: Image Tertiary Public'},

    {'label':'text',            'value':'Please follow directions <a href="https://www.webmerge.me/blog/embed-images-in-word-docx">here</a> and remember to append <code>|image:1:png</code> to the image placeholder. Your finished merge variable should look something like <code>{$Property_Image_Primary|image:1:png}</code>.'},
    {'label':'text',            'value':'View the linked image below in a new tab and modify the height/width parameters so that the image fits in your document. Once properly sized, right-click and copy/paste into your document.<br><br><a href="https://www.webmerge.me/images/image.php?width=300&amp;height=100&amp;type=png">https://www.webmerge.me/images/image.php?width=300&amp;height=100&amp;type=png</a>'},
    {'label':'text',            'value':'NEW METHOD: <code>{$Property_Image_Primary|insert_image:300:100}</code> where width = 300, height = 100.'},

  //############################################################################
  {'label':'header',        'value':'Transaction'},
  //############################################################################


    {'label':'subheader',                                 'value':'Earnest Money'},
      {'label':'Earnest Money',                           'value':'Earnest Money (Sale)'},
      {'label':'Earnest Money Amount',                    'value':'Earnest Money Amount'},
      {'label':'Close Date ',                             'value':'Close Date|date_format:"F j, Y"'},
      {'label':'Due Diligence Period Expiration Date',    'value':'Due Diligence Period Expiration Date|date_format:"F j, Y"'},

   

    {'label':'subheader',                                 'value':'Residual Commission Details'},
      {'label':'Gross Residual Commission Dollars',        'value':'Gross Residual Commission Dollars'},
      {'label':'Gross Residual Commission Percent',        'value':'Gross Residual Commission Percent'},
      {'label':'Company Residual Commission Dollars',      'value':'Company Residual Commission Dollars'},
      {'label':'Company Residual Commission Percent',      'value':'Company Residual Commission Percent'},
      {'label':'Co-Broker Residual Commission Dollars',   'value':'Co Broker Residual Commission Dollars'},
      {'label':'Co-Broker Residual Commission Percent',    'value':'Co Broker Residual Commission Percent'},
      {'label':'Residual Commission First Mo Dollars',     'value':'Residual Commission First Mo Dollars'},
      {'label':'Residual Commission First Mo Percent',     'value':'Residual Commission First Mo Percent'},
      {'label':'Residual Commission Remaining Mo Dollars', 'value':'Residual Commission Remaining Mo Dollars'},
      {'label':'Residual Commission Remaining Mo Percent', 'value':'Residual Commission Remaining Mo Percent'},

    {'label':'subheader',                     'value':'LeaseTransaction Info'},
      {'label':'Lease Commencement Date',     'value':'Lease Commencement Date|date_format:"F j, Y"'},
      {'label':'Lease Expiration Date',       'value':'Lease Expiration Date|date_format:"F j, Y"'},
      {'label':'Lease Term (Months)',         'value':'Lease Term Months'},
      {'label':'Security Deposit (Yes/No)',   'value':'Security Deposit'},
      {'label':'Security Deposit Amount',     'value':'Security Deposit Amount'},
      {'label':'Security Deposit Held By',    'value':'Security Deposit Held By'},
      {'label':'Base Year',                   'value':'Base Year'},

  //############################################################################
  {'label':'header',        'value':'Contact'},
  //############################################################################

    {'label':'subheader',         'value':'Buyer Acount'},
      {'label':'Account Name',    'value':'Buyer Account: Account Name'},
      {'label':'Street Address',  'value':'Buyer Account: Billing Street'},
      {'label':'City',            'value':'Buyer Account: Billing City'},
      {'label':'State',           'value':'Buyer Account: Billing State Province'},
      {'label':'Zipcode',         'value':'Buyer Account: Billing Zip Postal Code'},
      {'label':'Country',         'value':'Buyer Account: Billing Country'},
	  {'label':'Type',            'value':'Buyer Account: Account Type'},
	  {'label':'Company Status',  'value':'Buyer Account: Company Status'},
	  {'label':'Industry',        'value':'Buyer Account: Industry'},
	  {'label':'Phone',        	  'value':'Buyer Account: Account Phone'},
	  {'label':'Fax',        	  'value':'Buyer Account: Account Fax'},
	  {'label':'Website',         'value':'Buyer Account: Website'},
	  {'label':'Number Of Days',  'value':'Buyer Account: Number Of Days'},
	  {'label':'Company Type',  'value':'Buyer Account: Company Type'},
	  {'label':'Upsell Opportunity',  'value':'Buyer Account: Upsell Opportunity'},
	  
	  
	  
	  

    {'label':'subheader',         'value':'Buyer Contact (Primary)'},
      {'label':'Full Name',       'value':'Primary Buyer Contact: Full Name'},
      {'label':'First Name',      'value':'Primary Buyer Contact: First Name'},
      {'label':'Last Name',       'value':'Primary Buyer Contact: Last Name'},
      {'label':'Title',           'value':'Primary Buyer Contact: Title'},
      {'label':'Department',      'value':'Primary Buyer Contact: Department'},
      {'label':'Email',           'value':'Primary Buyer Contact: Email'},
      {'label':'Fax',             'value':'Primary Buyer Contact: Business Fax'},
      {'label':'Phone',           'value':'Primary Buyer Contact: Business Phone'},
      {'label':'Mobile Phone',    'value':'Primary Buyer Contact: Mobile Phone'},
	  {'label':'Company',         'value':'Primary Buyer Contact: Company'},
	  {'label':'Contact Status',  'value':'Primary Buyer Contact: Contact Status'},
	  {'label':'Contact Type',    'value':'Primary Buyer Contact: Contact Type'},
	  {'label':'Industry',        'value':'Primary Buyer Contact: Industry'},
	  {'label':'Source',          'value':'Primary Buyer Contact: Source'},
	  
	  
	  
	  

    {'label':'subheader',         'value':'Seller Acount'},
      {'label':'Account Name',    'value':'Seller Account: Account Name'},
      {'label':'Street Address',  'value':'Seller Account: Billing Street'},
      {'label':'City',            'value':'Seller Account: Billing City'},
      {'label':'State',           'value':'Seller Account: Billing State Province'},
      {'label':'Zipcode',         'value':'Seller Account: Billing Zip Postal Code'},
      {'label':'Country',         'value':'Seller Account: Billing Country'},
	  {'label':'Type',            'value':'Seller Account: Account Type'},
	  {'label':'Company Status',  'value':'Seller Account: Company Status'},
	  {'label':'Industry',        'value':'Seller Account: Industry'},
	  {'label':'Phone',        	  'value':'Seller Account: Account Phone'},
	  {'label':'Fax',        	  'value':'Seller Account: Account Fax'},
	  {'label':'Website',         'value':'Seller Account: Website'},
	  {'label':'Number Of Days',  'value':'Seller Account: Number Of Days'},
	  {'label':'Company Type',  'value':'Seller Account: Company Type'},
	  {'label':'Upsell Opportunity',  'value':'Seller Account: Upsell Opportunity'},

    {'label':'subheader',     'value':'Seller Contact (Primary)'},
      {'label':'Full Name',       'value':'Primary Seller Contact: Full Name'},
      {'label':'First Name',      'value':'Primary Seller Contact: First Name'},
      {'label':'Last Name',       'value':'Primary Seller Contact: Last Name'},
      {'label':'Title',           'value':'Primary Seller Contact: Title'},
      {'label':'Department',      'value':'Primary Seller Contact: Department'},
      {'label':'Email',           'value':'Primary Seller Contact: Email'},
      {'label':'Fax',             'value':'Primary Seller Contact: Business Fax'},
      {'label':'Phone',           'value':'Primary Seller Contact: Business Phone'},
      {'label':'Mobile Phone',    'value':'Primary Seller Contact: Mobile Phone'},
	  {'label':'Company',         'value':'Primary Seller Contact: Company'},
	  {'label':'Contact Status',  'value':'Primary Seller Contact: Contact Status'},
	  {'label':'Contact Type',    'value':'Primary Seller Contact: Contact Type'},
	  {'label':'Industry',        'value':'Primary Seller Contact: Industry'},
	  {'label':'Source',          'value':'Primary Seller Contact: Source'},

    {'label':'subheader',         'value':'Landlord Acount'},
      {'label':'Account Name',    'value':'Landlord Account: Account Name'},
      {'label':'Street Address',  'value':'Landlord Account: Billing Street'},
      {'label':'City',            'value':'Landlord Account: Billing City'},
      {'label':'State',           'value':'Landlord Account: Billing State Province'},
      {'label':'Zipcode',         'value':'Landlord Account: Billing Zip Postal Code'},
      {'label':'Country',         'value':'Landlord Account: Billing Country'},
	  {'label':'Type',            'value':'Landlord Account: Account Type'},
	  {'label':'Company Status',  'value':'Landlord Account: Company Status'},
	  {'label':'Industry',        'value':'Landlord Account: Industry'},
	  {'label':'Phone',        	  'value':'Landlord Account: Account Phone'},
	  {'label':'Fax',        	  'value':'Landlord Account: Account Fax'},
	  {'label':'Website',         'value':'Landlord Account: Website'},
	  {'label':'Number Of Days',  'value':'Landlord Account: Number Of Days'},
	  {'label':'Company Type',  'value':'Landlord Account: Company Type'},
	  {'label':'Upsell Opportunity',  'value':'Landlord Account: Upsell Opportunity'},

    {'label':'subheader',     'value':'Landlord Contact (Primary)'},
      {'label':'Full Name',       'value':'Primary Landlord Contact: Full Name'},
      {'label':'First Name',      'value':'Primary Landlord Contact: First Name'},
      {'label':'Last Name',       'value':'Primary Landlord Contact: Last Name'},
      {'label':'Title',           'value':'Primary Landlord Contact: Title'},
      {'label':'Department',      'value':'Primary Landlord Contact: Department'},
      {'label':'Email',           'value':'Primary Landlord Contact: Email'},
      {'label':'Fax',             'value':'Primary Landlord Contact: Business Fax'},
      {'label':'Phone',           'value':'Primary Landlord Contact: Business Phone'},
      {'label':'Mobile Phone',    'value':'Primary Landlord Contact: Mobile Phone'},
	  {'label':'Company',         'value':'Primary Landlord  Contact: Company'},
	  {'label':'Contact Status',  'value':'Primary Landlord  Contact: Contact Status'},
	  {'label':'Contact Type',    'value':'Primary Landlord  Contact: Contact Type'},
	  {'label':'Industry',        'value':'Primary Landlord  Contact: Industry'},
	  {'label':'Source',          'value':'Primary Landlord  Contact: Source'},

    {'label':'subheader',         'value':'Tenant Acount'},
      {'label':'Account Name',    'value':'Tenant Account: Account Name'},
      {'label':'Street Address',  'value':'Tenant Account: Billing Street'},
      {'label':'City',            'value':'Tenant Account: Billing City'},
      {'label':'State',           'value':'Tenant Account: Billing State Province'},
      {'label':'Zipcode',         'value':'Tenant Account: Billing Zip Postal Code'},
      {'label':'Country',         'value':'Tenant Account: Billing Country'},
	  {'label':'Type',            'value':'Tenant Account: Account Type'},
	  {'label':'Company Status',  'value':'Tenant Account: Company Status'},
	  {'label':'Industry',        'value':'Tenant Account: Industry'},
	  {'label':'Phone',        	  'value':'Tenant Account: Account Phone'},
	  {'label':'Fax',        	  'value':'Tenant Account: Account Fax'},
	  {'label':'Website',         'value':'Tenant Account: Website'},
	  {'label':'Number Of Days',  'value':'Tenant Account: Number Of Days'},
	  {'label':'Company Type',  'value':'Tenant Account: Company Type'},
	  {'label':'Upsell Opportunity',  'value':'Tenant Account: Upsell Opportunity'},
	  

    {'label':'subheader',     'value':'Tenant Contact (Primary)'},
      {'label':'Full Name',       'value':'Primary Tenant Contact: Full Name'},
      {'label':'First Name',      'value':'Primary Tenant Contact: First Name'},
      {'label':'Last Name',       'value':'Primary Tenant Contact: Last Name'},
      {'label':'Title',           'value':'Primary Tenant Contact: Title'},
      {'label':'Department',      'value':'Primary Tenant Contact: Department'},
      {'label':'Email',           'value':'Primary Tenant Contact: Email'},
      {'label':'Fax',             'value':'Primary Tenant Contact: Business Fax'},
      {'label':'Phone',           'value':'Primary Tenant Contact: Business Phone'},
      {'label':'Mobile Phone',    'value':'Primary Tenant Contact: Mobile Phone'},
	  {'label':'Company',         'value':'Primary Tenant Contact: Company'},
	  {'label':'Contact Status',  'value':'Primary Tenant Contact: Contact Status'},
	  {'label':'Contact Type',    'value':'Primary Tenant Contact: Contact Type'},
	  {'label':'Industry',        'value':'Primary Tenant Contact: Industry'},
	  {'label':'Source',          'value':'Primary Tenant Contact: Source'},

    {'label':'subheader',     'value':'Co-Broker Acount'},
      {'label':'Account Name',    'value':'Co-Broker Account: Account Name'},
      {'label':'Street Address',  'value':'Co-Broker Account: Billing Street'},
      {'label':'City',            'value':'Co-Broker Account: Billing City'},
      {'label':'State',           'value':'Co-Broker Account: Billing State Province'},
      {'label':'Zipcode',         'value':'Co-Broker Account: Billing Zip Postal Code'},
      {'label':'Country',         'value':'Co-Broker Account: Billing Country'},
	  {'label':'Type',            'value':'Co-Broker Account: Account Type'},
	  {'label':'Company Status',  'value':'Co-Broker Account: Company Status'},
	  {'label':'Industry',        'value':'Co-Broker Account: Industry'},
	  {'label':'Phone',        	  'value':'Co-Broker Account: Account Phone'},
	  {'label':'Fax',        	  'value':'Co-Broker Account: Account Fax'},
	  {'label':'Website',         'value':'Co-Broker Account: Website'},
	  {'label':'Number Of Days',  'value':'Co-Broker Account: Number Of Days'},
	  {'label':'Company Type',  'value':'Co-Broker Account: Company Type'},
	  {'label':'Upsell Opportunity',  'value':'Co-Broker Account: Upsell Opportunity'},

    {'label':'subheader',     'value':'Co-Broker Contact (Primary)'},
      {'label':'Full Name',       'value':'Co-Broker Contact: Full Name'},
      {'label':'First Name',      'value':'Co-Broker Contact: First Name'},
      {'label':'Last Name',       'value':'Co-Broker Contact: Last Name'},
      {'label':'Title',           'value':'Co-Broker Contact: Title'},
      {'label':'Department',      'value':'Co-Broker Contact: Department'},
      {'label':'Email',           'value':'Co-Broker Contact: Email'},
      {'label':'Fax',             'value':'Co-Broker Contact: Business Fax'},
      {'label':'Phone',           'value':'Co-Broker Contact: Business Phone'},
      {'label':'Mobile Phone',    'value':'Co-Broker Contact: Mobile Phone'},
	  {'label':'Company',         'value':'Co-Broker Contact: Company'},
	  {'label':'Contact Status',  'value':'Co-Broker Contact: Contact Status'},
	  {'label':'Contact Type',    'value':'Co-Broker Contact: Contact Type'},
	  {'label':'Industry',        'value':'Co-Broker Contact: Industry'},
	  {'label':'Source',          'value':'Co-Broker Contact: Source'},
	  

    {'label':'subheader',     'value':'Created By (The user who created the record)'},
      {'label':'Full Name',       'value':'Created By: Full Name'},
      {'label':'First Name',      'value':'Created By: First Name'},
      {'label':'Last Name',       'value':'Created By: Last Name'},
      {'label':'Company Name',    'value':'Created By: Company Name'},
      {'label':'Street Address',  'value':'Created By: Street'},
      {'label':'City',            'value':'Created By: City'},
      {'label':'State',           'value':'Created By: State Province'},
      {'label':'Zip',             'value':'Created By: Zip Postal Code'},
      {'label':'Email',           'value':'Created By: Email'},
      {'label':'Phone',           'value':'Created By: Phone'},
      {'label':'Fax',             'value':'Created By: Fax'},
      {'label':'Cell',           'value':'Created By: Cell'},

  //############################################################################
  {'label':'header',        'value':'Date'},
  //############################################################################

    {'label':'subheader',                 'value':'Date Formats'},
      {'label':'Listing Commencement',    'value':'Listing Agreement Commencement Date|date_format:"F j, Y"'},
      {'label':'Listing Expiration',      'value':'Listing Agreement Expiration Date|date_format:"F j, Y"'},
      {'label':'Create Date',             'value':'Created By Created Date|date_format:"F j, Y"'},
      {'label':'Lease Commencement',      'value':'Lease Commencement Date'},
      {'label':'Lease Expiration',        'value':'Lease Expiration Date'},
      {'label':'Option to Renew',         'value':'Option to Renew'},
      {'label':'Option to Terminate',     'value':'Option to Terminate'},
      {'label':'Due Diligence',           'value':'Due Diligence Period Expiration Date'},
      {'label':'text',                    'value': '<code>|date_format\:"F j, Y"</code> produces March 1, 2016.'},
      {'label':'text',                    'value': '<code>|date_format\:"m/d/Y"</code> produces 03/01/2016.'},

  //############################################################################
  {'label':'header',        'value':'Rent Table'},
  //############################################################################

    {'label':'subheader',                 'value':'Rent Table'},
      {'label':'text',                    'value': 'Please copy/paste from the <a href="RentTableMerge.docx">Rent Table Document</a>.'}


];
